### ISSUE TITLE
Miss understanding some input and output parameters

### ISSUE THREAD

**Issue by MansourTrabelsi** [Baksonator/evolutionary-timetable-scheduling#1]
Thank you for your solution, I am so exciting to execute it with my data, but i am falling in the miss understand of some parameters.
1. In the input json for example, can you please explain the meaning of the "Ucionice" parameters ("a", "k", "n", "r", "s").
` "Ucionice": {
		"a": ["Atelje"],
		"k": ["Kolarac"],
		"n": ["U1", "U8"],
		"r": ["U3", "U4", "U5", "U7"],
		"s": ["Studio"]
	} `
2. Also in the same file, the "Tip" key, have values like "V" and "P", "L",
 ` "Tip": "V" `
can you precise more their meaning.
3. When i found more than one groupe in the "Grupe" parameter, does this means that those groupes study all together in the same room and in the same subject and the same professor ?
4. Also the number of hours introduced in the "Trajanje" parameter like this 
` "Trajanje": "2" `
is it the number of hours, or is it the number of session or what ?

Thank you a lot.

**Comment by Baksonator** [comment]
Hey Mansour,

I am glad that you are finding my contribution useful! I'll try my best to help you with your questions.

1. As for the `"Ucionice"` json object, you will notice that there is also a `"Ucionica"` key as part of the `"Casovi"` object below. The `"Ucionice"` object holds the types of classrooms that I have at university, and each type has a list of classrooms that belong to it (i.e. classrooms `"U1"` and `"U8"` are of type `"n"`). The `"Ucionica"` key in `"Casovi"` holds a type of classroom that is needed for that particular class, and it has a value of either `"a", "k", "n", "r" or "s"` in this example. If you take a closer look in the `"data.py"` script, you'll notice that when I load the data, I actually change the `"Ucionica"` key to not store the type of classrooms that are allowed, and I instead place a list of classrooms that are allowed there, so that I can manipulate them more easily. For example, if a class had this parameter: `"Ucionica": "n"`, I change it so that it looks like: `"Ucionica": ["U1, "U8"]`.

2. The "Tip" key stands for Type of Class, and the value that it can have are the following:
P - Regular lecture
V - Practical
L - Lab practical (something we have here in Serbia, this might not be the same for you)

3. Yes, that is precisely what it means.

4. The value of the "Trajanje" parameter is indeed the number of hours that class is held for.

If there is anything else you need help with, feel free to ask, I'll be happy to help!
