### ISSUE TITLE
Adding professor availibility in the constraints

### ISSUE THREAD

**Issue by MansourTrabelsi** [Baksonator/evolutionary-timetable-scheduling#2]
Hi,

Thank you for your help concerning the last issue. It helped me a lot.
Now, I am dealing with the idea of adding the avalibility of a professor. So, you are creating the list of sessions of each professor like this :
`professors[single_class['Teacher']] = [0] * 25`
which will generate a list of 25 zeros (I have 5 session per day, so i get 25 sessions per 5 days, 3 sessions AM, and two others PM). I am thinking to replace the '0' by '-1' when a professor is not available at that time to get a list like this : 
`[-1,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]`
that list indicates that this professor is not available on monday.
My question now, is where to satisify this hard constraint ?

Thank you a lot.

**Comment by Baksonator** [comment]
Hi,

Sorry for the late answer, I did not notice the issue.

Well, they way I implemented the solution, if there was a 1 in a session, that meant that professor is not available in that period of time anymore, because he is holding one class in that period. Then, if there was a 2 or a 3 or more, it meant he was supposed to hold more classes in that period, which is impossible, and I penalized that. So, if you want to not allow for a professor to have a class on Mondays, just put all 1's on Monday before starting the algorithm, and it will avoid assigning that professor classes on Monday.

Hope this helps, let me know if it doesn't.
